theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true  
github:
  is_project_page: false
 
title: Conversational End-to-End TTS for Voice Agents
description:
  Haohan Guo, Shaofei Zhang, Frank K. Soong, Lei He, Lei Xie <br>
  Audio, Speech and Language Processing Group (ASLP@NPU), School of Computer Science, Northwestern Polytechnical University, Xi’an, China <br>
  Microsoft China <br>
